# Create a new expense
# @name addExpense
POST http://localhost:8000/expenses
Content-Type: application/json

{
  "title": "Dinner with friends",
  "payment_type": "card",
  "description": "Dinner at a fancy restaurant",
  "value": 120.00
}

###

# List all expenses
GET http://localhost:8000/expenses

###

# Get a expense by ID
@expenseID = {{addExpense.response.body.data.id}}
GET http://localhost:8000/expenses/{{expenseID}}

###

# Delete a expense by ID
@expenseID = {{addExpense.response.body.data.id}}
DELETE http://localhost:8000/expenses/{{expenseID}}
