services:
  db:
    image: bitnami/postgresql:15.4.0
    container_name: postgres_db_mymoney
    ports:
      - "15432:5432"
    restart: always
    environment:
      - POSTGRES_USER=naves
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=mymoney
    volumes:
      - mymoney_db_data:/bitnami/postgresql

volumes:
  mymoney_db_data: